=pod

=head1 Praati

Praati is web software for criticizing and listening music within
a small group of people.  Users may register themselves, listen some
songs, and then rate them and add comments.  Once they have done,
the songs can be listened to in some order (from the worst to the
best, generally) and everyone's ratings and comments can be seen.
The critics should rate and comment songs privately, in preparation
for the final listening session that is intended to happen so that
everyone will gather together for it.

A kind of normalization is done for user ratings.  The user rating
correlations is also calculated, so it can be seen how compatible
different users music tastes are.  These are calculated cumulatively,
so that only those songs that have been listened to are taken into
account.

Only mp3 files are supported.  This software has been developed and
tested on OpenBSD 5.5 with its own Apache version (a fork of 1.3).
It is probably possible to port it to other systems or Apache
versions with only little work.

There is no user manual, sorry.  Currently the user interface is
in Finnish (but you may tweak it to English easily).  You have to
figure out on your own how to install it and use it.  If you really
need help, contact the author.

This software has been written by Juha Erkkila <je@turnipsi.no-ip.org>.
Patches (portability, security, features, whatever) are mostly
welcome.  This software is in public domain, meaning that the author
disclaims copyright to the source code.

Praati was very much inspired by Graati
(L<https://github.com/starvinraven/graati>)
by Esa Virtanen (but shares none of the code).
